- frontend/src/components/canvas/CanvasPopover.tsx
- frontend/src/components/canvas/MyCanvas.tsx
- frontend/src/components/canvas/ZoomButtons.tsx
- frontend/src/components/sideBar/DrawModeToggleButton.tsx
- frontend/src/components/sideBar/SideBar.tsx
- frontend/src/context/DrawModeContext.tsx
- frontend/src/layouts/MainLayout.tsx
- frontend/src/pages/HomePage/MyCanvasLoader.tsx
- frontend/src/pages/HomePage/index.tsx
> More homepage styling

- frontend/src/components/canvas/DrawingCanvas.tsx
- frontend/src/components/canvas/MyCanvas.tsx
- frontend/src/components/canvas/StyledCanvasBox.tsx
- frontend/src/context/DrawModeContext.tsx
- frontend/src/layouts/MainLayout.tsx
> canvas styling

- frontend/src/components/canvas/CanvasPopover.tsx
- frontend/src/components/canvas/MyCanvas.tsx
- frontend/src/components/canvas/SubmitDrawButton.tsx
* remove old logic for single pixel submission and popover
* move the transaction submitting logic to a submit button component
* simplify popover component
> Submit button and popover refactor

- frontend/src/components/canvas/BottomComponentWrapper.tsx
- frontend/src/components/canvas/SubmitDrawButton.tsx
- frontend/src/components/sideBar/SideBar.tsx
> submit confirmation modal

- frontend/src/components/canvas/DrawingCanvas.tsx
- frontend/src/components/canvas/ZoomButtons.tsx
> Zoom buttons styling

- frontend/src/components/sideBar/Palette.tsx
- frontend/src/components/sideBar/SideBar.tsx
- frontend/src/components/sideBar/SizeSlider.tsx
- frontend/src/context/DrawModeContext.tsx
> Sidebar yay

- frontend/src/components/canvas/MyCanvas.tsx
- frontend/src/components/canvas/SubmitDrawButton.tsx
> Clear canvas button

- frontend2/src/components/Canvas/drawingImage.ts
- frontend2/src/components/Canvas/index.tsx
- frontend2/src/components/Canvas/types.ts
This should make drawing a little more accurate
> Improve drawing algorithm to ensure continuous lines

- frontend2/src/app/(home)/DesktopCanvasHeader.tsx
- frontend2/src/app/(home)/DesktopSidePanel.tsx
- frontend2/src/app/(home)/MobileCanvasFooter.tsx
- frontend2/src/app/(home)/MobileCanvasHeader.tsx
- frontend2/src/app/(home)/MobileCanvasSidePanel.tsx
- frontend2/src/app/(home)/MobileHeader.tsx
- frontend2/src/app/(home)/page.tsx
- frontend2/src/components/Canvas/drawingImage.ts
- frontend2/src/components/Canvas/index.tsx
- frontend2/src/components/DrawingControls/PaintInfo.tsx
- frontend2/src/components/DrawingControls/StrokeColorSelector.tsx
This implements drawing on mobile with stroke color and width selection. No pan or zoom yet, but it's coming soon
> Implement drawing on mobile

- frontend2/public/identity-connect.txt
This doesn't cause problems now, but is possibly messing with a few things, this is supposed to be done for any ic app
> Add IC public file

- frontend2/src/components/Canvas/index.tsx
- frontend2/src/components/CanvasActions/index.tsx
Also added more consistent wording to the submit button
> Increase default zoom

- frontend2/src/components/Canvas/gestures.ts
- frontend2/src/components/Canvas/index.tsx
- frontend2/src/constants/canvas.ts
https://github.com/aptos-labs/graffio/assets/25761639/0ca87504-1d17-4a38-9b32-982c5f386419
> Zoom in and out when switching modes

- frontend2/src/app/(home)/DesktopCanvasHeader.tsx
- frontend2/src/app/(home)/MobileCanvasHeader.tsx
- frontend2/src/components/Countdown/index.tsx
> Add launch countdown

- frontend2/package.json
- frontend2/pnpm-lock.yaml
To include https://github.com/aptos-labs/identity-connect/pull/260
Tested in it works properly on all browsers in development mode
> Bumped `@identity-connect/wallet-adapter-plugin` to 1.0.8

- frontend2/src/components/CanvasActions/index.tsx
- frontend2/src/components/Countdown/index.tsx
No actual terms yet, but the text and link is there.
> Add terms copy in header

- frontend2/.env.example
- frontend2/src/app/GoogleAnalytics.tsx
- frontend2/src/app/layout.tsx
We'll still want to add some custom events later, but this should allow us to at least start collecting some basic metrics.
> Add Google Analytics to project

- frontend2/src/components/Countdown/index.tsx
This also fixes a hydration HTML mismatch error
> Update launch time

- frontend2/src/components/Canvas/drawImage.ts
- frontend2/src/components/Canvas/index.tsx
- frontend2/src/components/CanvasActions/index.tsx
https://github.com/aptos-labs/graffio/assets/25761639/f43063ca-8063-46a7-ba42-65fc4b2d68d8
> Enforce 5 second cool down

- backend/configs/example_testnet.yaml
- backend/flusher/src/lib.rs
- backend/flusher/src/local.rs
- backend/move-types/src/objects.rs
- backend/pixel-storage/src/lib.rs
- backend/pixel-storage/src/mmap.rs
- backend/pixel-storage/src/utils.rs
- backend/processor/src/processor.rs
This PR updates the processor in response to https://github.com/aptos-labs/graffio/pull/85.
> Handle hardcoded colors in the processor

- frontend2/src/components/Canvas/drawImage.ts
- frontend2/src/components/CanvasActions/index.tsx
- frontend2/src/components/ConnectWalletModal/index.tsx
- frontend2/src/components/ConnectWalletModal/useCanDrawUnlimited.ts
- frontend2/src/components/Countdown/index.tsx
- frontend2/src/components/DrawingControls/PaintInfo.tsx
- frontend2/src/constants/abi.ts
- frontend2/src/constants/config.ts
- frontend2/src/contexts/canvas.ts
- frontend2/src/contexts/wallet.tsx
Also changes the launch time to the close time
> Make mainnet the default

- frontend2/package.json
- frontend2/pnpm-lock.yaml
https://github.com/aptos-labs/graffio/assets/7707719/9fbee9de-885c-44be-93dc-28875d710aa9
> Auto disconnect expired pairing (bumped `@identity-connect/wallet-adapter-plugin` to 1.0.11)

- frontend2/src/components/CanvasActions/index.tsx
- frontend2/src/components/ConnectWalletModal/index.tsx
- frontend2/src/components/DrawingControls/PaintInfo.tsx
- frontend2/src/contexts/canvas.ts
> Support drawing paused mode

- frontend2/src/components/Canvas/keyboardShortcuts.ts
- frontend2/src/components/CanvasOverlay/OtherActions.tsx
- frontend2/src/components/ControlsModal/DesktopControlsModal.tsx
- frontend2/src/components/ControlsModal/index.tsx
- frontend2/src/components/Icons/CloseIcon.tsx
> Add desktop controls modal

- frontend2/src/components/Canvas/index.tsx
- frontend2/src/components/DrawingControls/PaintInfo.tsx
- frontend2/src/contexts/canvas.ts
- frontend2/src/utils/useWarnBeforeUnload.ts
https://github.com/aptos-labs/graffio/assets/25761639/f971c302-67e8-4493-9f58-aa0495986711
> Warn user before page unload

- frontend2/package.json
- frontend2/pnpm-lock.yaml
- frontend2/src/contexts/wallet.tsx
Removing fewcha to make sure only IC supported wallets are available for use
> Remove fewcha

- frontend2/src/components/ConnectWalletModal/index.tsx
> Add hyperlink connect wallet in toast

- frontend2/.env.example
- frontend2/package.json
- frontend2/patches/@aptos-labs__wallet-adapter-core@2.5.1.patch
- frontend2/pnpm-lock.yaml
- frontend2/src/app/(home)/MobileCanvasFooter.tsx
- frontend2/src/components/CanvasActions/index.tsx
- frontend2/src/components/ConnectWalletModal/index.tsx
- frontend2/src/components/ControlsModal/DesktopControlsModal.tsx
- frontend2/src/components/Countdown/index.tsx
- frontend2/src/components/DrawingControls/DrawModeToggle.tsx
- frontend2/src/components/EndStateContent/ExportWalletButton.tsx
- frontend2/src/components/EndStateContent/ViewNftButton.tsx
- frontend2/src/components/EndStateContent/index.tsx
- frontend2/src/components/EndStateContent/useEndStateToast.tsx
- frontend2/src/components/Toast/Toast.tsx
- frontend2/src/contexts/canvas.ts
- frontend2/src/utils/parseError.ts
> Add end state for Graffio
